### ISSUE TITLE
Allow arrow functions

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/create-wordpress-plugin#136]
When trying to change a block `edit.js` file to use an arrow function, project config is forcing regular function. Unless there is a good reason, it should be dealer’s choice.

**Comment by stevenslack** [comment]
Functional components are the preferred pattern in React. Additionally the extended Airbnb ESLint rules enforce them as you have noticed. We are enforcing them here as well. There is a rich history. This article does a decent job of explaining this change: https://hackernoon.com/react-functional-components-are-the-future

**Comment by renatonascalves** [comment]
This feels more like an encouragement than a "I'll force you to use this because I think this is the future". There is nothing inherently wrong with a React arrow function component (I'd love to hear if it is). Also, since this is an open source template, this should not be forced, but encouraged.

**Comment by stevenslack** [comment]
By adopting the Airbnb ESLint rules without many customizations it is up to the developer to customize those rules in any particular project. If there is a need to remove a particular rule or make an exception it can be done in the extended ESLint config file.

**Comment by renatonascalves** [comment]
Thanks!
