### ISSUE TITLE
Block: Load block per post type

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/create-wordpress-plugin#138]
Currently, due to the way block assets are registered and loaded, there is no easy way to load them per post type;

💡 Make sure you load only the bock editor assets per post type, not the front-end assets which should be loaded when the block is used.

**Comment by stevenslack** [comment]
@renatonascalves the filter [`allowed_block_types_all`](https://developer.wordpress.org/reference/hooks/allowed_block_types_all/) can be used to allow certain blocks from showing on post types.
