### ISSUE TITLE
An alias for `npm run dev`

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/create-wordpress-plugin#269]
### Description

It looks like it used to be available, https://github.com/alleyinteractive/create-wordpress-plugin/blob/f3317f79304725eccc3027daa8482d1fb7153624/package.json#L24, but not anymore?!

A lot of devs have tools integrated to run `npm run dev` instead of `npm run start`. And having one project with `dev` and another with `start` creates unnecessary burden, since we can't upgrade all projects at once.

### Use Case

Devs with tooling integrated with `npm run dev` instead of `npm run start`.

**Comment by stevenslack** [comment]
`npm run start` is a derivative of using `wp-scripts start` used by [the `alley-build` command](https://github.com/alleyinteractive/alley-scripts/blob/main/packages/build-tool/README.md#usage). The commands should match their parent commands. Therefore the tools integrated here use `start` as this should as well.

The purpose of the `create-wordpress-plugin` is to quickly and easily scaffold a plugin. If the developers prefer to use `npm run dev` in a particular project that change can be made to the scripts in `package.json`. However, for the purposes of this project and for the reasons mentioned above, this script should remain with `start`

```diff
-    "predev": "check-node-version --package",
+    "prestart": "check-node-version --package",
```

**Comment by renatonascalves** [comment]
Tks for the reason. Sounds good!
