### ISSUE TITLE
[Node 18] Upgrade npm/node to match WP 6.4

### ISSUE THREAD

**Issue by attackant** [alleyinteractive/create-wordpress-plugin#281]
### Description

As titled. 

### Use Case

Would be great to get this up to date so new projects were current.

**Comment by srtfisher** [comment]
@attackant PHP 7.4 is already not supported:

- https://github.com/alleyinteractive/create-wordpress-plugin/blob/develop/README.md#L42
- https://github.com/alleyinteractive/create-wordpress-plugin/blob/develop/composer.json#L18
