### ISSUE TITLE
Support Windows Paths

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-plugin#296]
### Description of the bug

The code checks paths for "validity" by checking the return value of `validate_file` to ensure that it is `0`, but a valid Windows filepath on a Windows system will return `2`, making it so that this plugin cannot run on a Windows host (either for local development or via Windows Server).

### Steps To Reproduce

1. Install this plugin on Windows
2. Observe that Gutenberg blocks are not registered because the paths are deemed invalid

### Additional Information

Should replace the `validate_file` check to ensure it returns either `0` or `2`

**Comment by stevenslack** [comment]
I have a pull request to address this issue #297, It will need to be tested on a Windows.
