### ISSUE TITLE
meta.php requires a function in assets.php that can get deleted by configure process

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/create-wordpress-plugin#319]
### Description of the bug

The meta.php file uses function `validate_path` found in assets.php. If you tell the configure process that the plugin will not have built assets, assets.php gets deleted causing a fatal error when you try to activate the plugin.

### Steps To Reproduce

Run `php configure.php`
answer yes to "Do you want to delete the front-end files?"
Try to activate the plugin, you will get a fatal error.

**Comment by srtfisher** [comment]
I meant to PR it but I actually pushed it to `develop` 😭  https://github.com/alleyinteractive/create-wordpress-plugin/commit/d77f641c868648d823d7468030c24026e90df296
