### ISSUE TITLE
Replace Buddy with GitHub Actions

### ISSUE THREAD

**Issue by benpbolton** [alleyinteractive/create-wordpress-plugin#356]
## Description

Upgrading the project from Buddy to GitHub actions will ensure parity with other Alley projects, reduce costs, and allow leveraging 'shared' common workflows or actions.

## Acceptance Criteria

- All CI/CD pipelines (eg. PR tests or deployment) are replaced by equivalent GitHub actions
- Any secrets are recreated or moved to GitHub secrets (environment or otherwise)
- Buddy disabled for the project

**Comment by srtfisher** [comment]
Buddy was only used here to allow for internal projects that use the template to properly setup CI. We can disable it with no repercussions. Can we also migrate it to the newer set of actions (vs .github-based ones)?

**Comment by benpbolton** [comment]
I wonder if there's an elegant way to not need to repeat ourselves across `create-wordpress-*` projects? Eg. [this PR](https://github.com/alleyinteractive/create-wordpress-project/pull/101/files) in `create-wordpress-project` attempts to clean up the examples... perhaps we can leverage it somehow?

**Comment by srtfisher** [comment]
Resolved in #372 and Buddy removed from Alley org.
